# Skeleton global config.yaml for WA3
device: generic_android

trace-cmd:
  buffer_size: 102400
  report: false
  events: ['sched*', 'power*']


# Disable re-trying things that go wrong
max_retries: 0

# If any of the workloads fail during the initialization phase, don't bail out
# on the rest of the run
bail_on_init_failure: false

# Default result processors
result_processors: ['csv', 'status']
energy_measurement:
  instrument: acme_cape
  instrument_parameters:
    host: 10.65.34.1
    # If collecting on multiple channels, or another channel than iio:device0,
    # set them here:
    iio_devices: ['iio:device0']
